# Generated by Django 5.0.6 on 2024-09-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('age_requirement', models.PositiveIntegerField(blank=True, null=True)),
                ('hours_expected', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Community & Social Services', 'Community & Social Services'), ('Education & Literacy', 'Education & Literacy'), ('Health & Wellness', 'Health & Wellness'), ('Environmental & Conservation', 'Environmental & Conservation'), ('Animal Welfare', 'Animal Welfare'), ('Arts, Culture & Heritage', 'Arts, Culture & Heritage'), ('International & Global Causes', 'International & Global Causes'), ('Sports & Recreation', 'Sports & Recreation'), ('Human Rights & Advocacy', 'Human Rights & Advocacy'), ('Emergency & Disaster Relief', 'Emergency & Disaster Relief'), ('Religious & Faith-Based', 'Religious & Faith-Based'), ('Technology & Innovation', 'Technology & Innovation'), ('Civic & Public Service', 'Civic & Public Service'), ('Business, Leadership & Professional Development', 'Business, Leadership & Professional Development'), ('Youth & Children Services', 'Youth & Children Services'), ('Senior Citizens Support', 'Senior Citizens Support'), ('Special Events & Fundraising', 'Special Events & Fundraising'), ('Skill-Based Volunteering', 'Skill-Based Volunteering'), ('Media & Communications', 'Media & Communications'), ('Military & Veterans Support', 'Military & Veterans Support')], max_length=100)),
            ],
        ),
    ]
