# Generated by Django 5.0.6 on 2024-12-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_volunteeropportunities_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
