# Generated by Django 5.0.6 on 2024-12-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunities',
            name='posted_by',
            field=models.CharField(max_length=255),
        ),
    ]
