# Generated by Django 5.0.6 on 2024-12-31 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_volunteeropportunities_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization_Newsletter',
        ),
        migrations.AlterField(
            model_name='volunteeropportunities',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_opportunities', to='website.organization'),
        ),
    ]
