# Generated by Django 5.0.6 on 2025-01-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_student_city_remove_student_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunities',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
