# Generated by Django 5.0.6 on 2025-01-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_signuprequest_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_credited', models.PositiveIntegerField()),
                ('people_credited', models.PositiveIntegerField()),
                ('task_completed', models.BooleanField(default=False)),
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.signuprequest')),
            ],
        ),
    ]
