# Generated by Django 5.0.6 on 2025-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_organization_accepted_organization_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('document', models.FileField(blank=True, null=True, upload_to='org_documents/')),
                ('verification_code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
