# Generated by Django 5.0.6 on 2025-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_pendingorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
