# Generated by Django 5.0.6 on 2025-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_organization_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Credited', 'Credited')], default='Pending', max_length=10),
        ),
    ]
